### PR TITLE
Improved RecyclerView item click event

### PR DESCRIPTION
**Pull request by ramiloif**
The event moved to onBindViewHolder method so that you can get all the data according to the position and not only the Data that in the view

### CODE REVIEW

**Comment by afarber** [comment]
I do not want to merge it, but thanks

**Comment by ramiloif** [comment]
Why not ?

**Comment by afarber** [comment]
That's not an improvement, just matter of what the user wants to have

**Comment by ramiloif** [comment]
As I see it The on click method should receive the data from the data list An not from the view.

For example each item on list have name and link and when you click you want to open the link 
You'll not store the link URL in the view itself.

**Pull request closed without merging**
